image:
  - Visual Studio 2019
  - Ubuntu
  - macos

environment:
  matrix:
    - nodejs_version: "15"
    - nodejs_version: "14"
    - nodejs_version: "13"
    - nodejs_version: "12"
    - nodejs_version: "11"
    - nodejs_version: "10"
    - nodejs_version: "9"
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "5"
    - nodejs_version: "4"
    - nodejs_version: "0.12"
    - nodejs_version: "0.10"

for:
  - matrix:
      only:
        - image: Visual Studio 2019
    install:
      - ps: Install-Product node $env:nodejs_version
      - ps: if ($env:nodejs_version -eq '5') { npm i -g npm@4 }
      - cmd: npm install
    test_script:
      - cmd: node --version
      - cmd: npm --version
      - cmd: npm test

  - matrix:
      except:
        - image: Visual Studio 2019
    install:
      - sh: nvm install $nodejs_version
      - sh: if [ $nodejs_version -eq 5 ]; then npm i -g npm@4; fi
      - sh: npm install
    test_script:
      - sh: node --version
      - sh: npm --version
      - sh: npm test

build: off

version: "{build}"
